### ISSUE TITLE
[Question] Firefox Support

### ISSUE THREAD

**Issue by stefan2904** [r4gus/keylib#30]
Hi,

thanks for the library! I have a quick clarification question. In your README you state that the library's UHID interface (for communication with browsers) does not support, e.g., Firefox:

![image](https://github.com/r4gus/keylib/assets/527767/70e93af3-4038-4822-8e8e-eb4ce84a5a79)

However, [PassKeeZ](https://github.com/r4gus/keypass) - which appears to be using this library - is supporting Firefox and also relies on UHID. 

Can I ask what statement is true and/or what PassKeeZ is doing differently than the lib?

Thanks a lot!

**Comment by r4gus** [comment]
Hi, thanks for pointing this out. The statement is outdated. The UHID interface should work with all browsers as long as they are not sand boxed.

**Comment by r4gus** [comment]
@stefan2904 if this answers your question feel free to close the issue.
